"""Add required_skills to Mission and DRAFT status

Revision ID: 2f7c9c8dc8af
Revises: d96cfc8dcef0
Create Date: 2025-12-15 20:09:41.438566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7c9c8dc8af'
down_revision = 'd96cfc8dcef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###
